name: Publish Library to JFrog

on:
  push:
    branches:
      - main  # Runs on push to main branch (modify if needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js (match the version you use locally)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Run Unit Tests
      #- name: Run Tests
      #  run: npm test

      # Build the Library
      - name: Build the Library
        run: npm run build-prod

      # Authenticate to JFrog Artifactory
      - name: Configure NPM for JFrog
        run: |
          echo "//trialtoh1md.jfrog.io/artifactory/jfrog-test-npm/:_authToken=${{ secrets.JFROG_ACCESS_TOKEN }}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      # Publish to JFrog
      - name: Publish Package to JFrog
        run: npm publish --registry=https://trialtoh1md.jfrog.io/artifactory/jfrog-test-npm/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
